### ISSUE TITLE
UUencode vs base64?

### ISSUE THREAD

**Issue by d-hat** [CVEProject/automation-working-group#10]
This choice looks like it could be considered:  UU includes permissions (useless here?) and filename (perhaps redundant as it looks like that is included in the JSON container object?).  Base64 is marginally simpler and more common today.

Also, the UU charset includes " and \ which need to be escaped in JSON strings

**Comment by d-hat** [comment]
worth bearing in mind that URLs are ephemeral:  a CVE document may want to be processed to fetch all URLs so that if they go offline, they are not lost.

suggests that a file+url should be simply transformed into a file+base64 content.

might also be worth supporting "relative urls", for files that are stored in the same repository as the CVE document but not inline in a massive JSON document.  I guess the URL field can already be used like this.

This thought makes me wonder:  should there be a top-level field "canonical_url", which describes where the CVE JSON originally came from?  Serves the same purpose as <base href> in html, as well as making it easy for a repository of CVE documents to be scanned for updates.

**Comment by d-hat** [comment]
From a comment in the document:

> we may require a compressed format so the objects require unpacking before they are "dangerous"

For safety, it's best to limit the available compression schemes.  I suggest "compress", "deflate", "gzip" as specified by zlib: all of these are well-known and safe.  [gzip quines](https://research.swtch.com/zip) should not be a problem as objects will only be decompressed once.

Supporting obfuscation so as to not trigger AV has its merits, but I'm a little hesitant about Zip because it's a container for multiple files.  crypt(1) no longer exists ... [ccrypt](https://ccrypt.sourceforge.net)?  aes256cbc?  The encryption need not be strong (indeed, the password must be present in the JSON), but tooling must be ubiquitous and decryption a no-brainer on all platforms.

**Comment by kurtseifried** [comment]
Added a note about base64, uuencode/decode fill the common case (POSIX based file system) where we would want to preserve name/file permissions when it matters). As for URLS the DWF plan (I can't speak to MITRE/other root CNAs) is to ideally embed artifacts within the JSON file so that if a website is not available, we have a copy in the database. As for actual compression/etc we need to think about this a bit more (e.g. which ones are the safest? do we want to actively avoid anti virus scanners because false positives? what other issues are there...).

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
