### ISSUE TITLE
specify date format as iso8601

### ISSUE THREAD

**Issue by d-hat** [CVEProject/automation-working-group#11]
it's obvious to most, but best to be explicit!

Not sure if a comment about TZ belongs here ... if I create a CVE in the morning Australian time but it's still yesterday in the US?  yesterday in Greenwich?  That's a mild/benign source of confusion in many places today - perhaps specifying that it's UTC-based "unless otherwise specified" is a good default.

**Comment by kurtseifried** [comment]
that was specified in previous drafts, updated this one to include it.
