### ISSUE TITLE
Three dateUpdated fields, all set by Services

### ISSUE THREAD

**Issue by zmanion** [CVEProject/automation-working-group#120]
1. [dateUpdated](https://cveproject.github.io/cve-schema/schema/v5.0/docs/#oneOf_i0_cveMetadata_dateUpdated) for the CVE record

2. [dateUpdated](https://cveproject.github.io/cve-schema/schema/v5.0/docs/#oneOf_i0_containers_cna_providerMetadata_dateUpdated) for the CNA container
Timestamp to be set by the system of record at time of submission. If dateUpdated is provided to the system of record it will be replaced by the current timestamp at the time of submission.

3. dateUpdated for the ADP container, same treatment as 2.

As noted in 2., if CNAs or ADPs provide dateUpdated, it gets stomped by the Services. So consider not allowing submission of these fields.

**Comment by zmanion** [comment]
See also https://github.com/CVEProject/cve-schema/issues/291, this issue seems to involve an interaction between CVE Record Format and CVE Services.

**Comment by mprpic** [comment]
I think it's enough to track this in the cve-schema repo from where, if needed, we can also file a CVE Services issue if one is required. Feel free to re-open if you disagree!
