### ISSUE TITLE
Removing AWG Members (Charter Review) 

### ISSUE THREAD

**Issue by jgamblin** [CVEProject/automation-working-group#129]
[This section](https://github.com/jgamblin/automation-working-group/blob/master/AWG_Charter.md#removing-awg-members
) doesn't clearly state how a person or organization is removed.   

>A current AWG member nominates the person or organization for forced removal. Forced removal may be based on lack of collegiality or professional conduct or failure to follow conventions as established in this Charter.

Is it by a simple vote of all members, members at the meeting, or the chair's discretion?  Is there an appeal process?

**Comment by mprpic** [comment]
This topic was discussed at the Jun 4, 2022 AWG meeting and the decision was that if the AWG ever feels the need to remove a member from the group, it will be passed on to the CVE board for a decision and to take action. Thus, no changes are currently required in the charter. Should this guidance not be sufficient enough, we can revisit this topic at a later date.
