### ISSUE TITLE
"strings separated by commas" needs clarification

### ISSUE THREAD

**Issue by d-hat** [CVEProject/automation-working-group#13]
This kind of thing appears several times in the spec+examples.  I'm not clear what it means:

  "cwe": ["string of cwes","strings separated by commas"]

Is the idea to support either one of:
   "cwe": ["CWE-123", "CWE-456"]
or:
   "cwe": "CWE-123,CWE-456"
?  Or something else?

This might be related to (final dot point first comment) issues/12 and perhaps indirectly to issues/8

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
