### ISSUE TITLE
Voting / Membership Question (Charter Review) 

### ISSUE THREAD

**Issue by jgamblin** [CVEProject/automation-working-group#130]
[Working Group Membership](https://github.com/jgamblin/automation-working-group/blob/master/AWG_Charter.md#working-group-membership)

> There is no limit to the number of representatives a given organization may have as members of the working group.

The charter clearly states there is no limit for membership for a given organization but should there a limitation to the number of votes per organization?  Hypothetically, an organization could have multiple members and undue influence.

**Comment by mprpic** [comment]
@jgamblin Do you have a proposal for what is a reasonable max number of voting members?

**Comment by jgamblin** [comment]
My thoughts are not to eliminate the number of votes per organization but to prevent a single organization from swaying a vote. 

Something like: 
"A single organization votes can only comprise up to 25% of all votes on a single issue."

**Comment by jgamblin** [comment]
You are right, this is not current issue.  We are working through a charter review and being one of the few truly open working groups with no membership limits it was just a thought that came up while I was reviewing it.

**Comment by jgamblin** [comment]
I created a PR with the following language:  

> The AWG membership is open to the public at large; this includes any [Board members](https://www.cve.org/ProgramOrganization/Board), [CVE Numbering Authority (CNA) representatives](https://www.cve.org/PartnerInformation/Partner#CNA), Authorized Data Publishers (ADP), participants from the Secretariat's organization and interested members of the wider community.  While there is no limit to the number of representatives an organization can have in the working group, any organization can only make up 25% of any recorded vote.

**Comment by mprpic** [comment]
PR was merged, closing this issue. Thanks, Jerry!
