### ISSUE TITLE
use CVSS JSON schema 

### ISSUE THREAD

**Issue by chandanbn** [CVEProject/automation-working-group#17]
Since a recommend JSON format for CVSS is available use that instead of current cvss element: https://www.first.org/cvss/cvss-v3.0.json
https://www.first.org/cvss/cvss-v2.0.json

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
