### ISSUE TITLE
The CVE_ prefix for reserved or documented keywords is unnecessary

### ISSUE THREAD

**Issue by chandanbn** [CVEProject/automation-working-group#19]
The CVE_ prefix for reserved or documented keywords seems unnecessary, (except for CVE_ID). Similar to how HTTP headers and extensions are named, anything on the documented list should be used as documented. An HTTP_ prefix is not required to make it official.

https://en.wikipedia.org/wiki/List_of_HTTP_header_fields

It is preferable to keep the names of most commonly used keywords simple, just like how we do not have HTTP_GET, HTTP_Accept-Encoding or SMTP_To, SMTP_From instead have a prefix for custom or vendor specific keywords for eg., X-OpenSSL-Severity-Rating or simply OpenSSL-Severity-Rating.

**Comment by kurtseifried** [comment]
having the CVE_ prefix allows parsers to easily know what they should be able to handle (e.g. if they encounter a tag starting with CVE_ that they don't know how to handle then they are out of spec, or the thing sending them data is out of spec if they are making up CVE_ tags) and which can safely be ignored (e.g. a company makes it's own tags for whatever reason, impact, etc.), and again notify the upstream if their internal data is escaping (and shouldn't be). You have to remember with federated CNA governance we'll have long chains of CNAs potentially.

**Comment by chandanbn** [comment]
You can achieve the same by providing a schema file that should help one easily check if a tag is out of spec or in spec. 'A lookup in a schema' sounds little more difficult to implement than a startsWith('CVE_') check, but is easily doable. IMHO doing this with a well defined schema is a cleaner and robust way of doing such a check.

Dropping 'CVE_' prefix would keep things simple and allow easy mapping or interoperation between other formats or tools. One should be able to copy paste relevant portions without having to map 'Workaround' to 'CVE_workaround', or 'Credit' to 'CVE_credit'.
