### ISSUE TITLE
Decide on upper case or lower case

### ISSUE THREAD

**Issue by kurtseifried** [CVEProject/automation-working-group#3]
MITRE uses lower case JSON tags I use upper case (e.g. data_version vs DATA_VERSION). I personally find the ALL UPPERCASE more readable/easier to differentiate, but obviously this is just an opinion. I do think we should decide on one or the other though.

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
