### ISSUE TITLE
Some simplifications

### ISSUE THREAD

**Issue by chandanbn** [CVEProject/automation-working-group#31]
It looks like there are a few containers (ending with *_data) add to unnecessary complexity.
Version 3.1 did not have this complexity, but may have crept in due to how the schema was copied forward to 4.0. They may be required as references within the schema definition, but are not really needed in the JSON itself. Any of the nesting aimed at encoding complex product/version situations or content from multiple editors/CNAs can still be done without them.

The complexity is obvious when you see the mindmap https://atlas.mindmup.com/2017/04/4995ec901bcc11e7a8271fd548147e6d/cve/index.html

This is a GUI Form auto generated from the current schema:
http://bit.ly/2nMpgcS

In comparison see this GUI from a simplification: (find my suggested schema down in that page)
http://bit.ly/2oaQvBr

This is an example that uses current schema:

```
affects: {
    vendor: {
        vendor_data: [
            {
                vendor_name: IETF,
                product: {
                    product_data: [
                        {
                            product_name: IP,
                            version: {
                                version_data: [
                                    {version_value: v4, impact: none},
                                    {version_value: v6, impact: hign}
                                ]
                            }
                        },
                        {
                            product_name: DHCP,
                            impact: none,
                            version: {
                                version_data: [
                                    {version_value: v4, impact: none},
                                    {version_value: v6, impact: none}
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    }
}

```
This is a simplified version with no loss of information or accuracy:
```

affects: [
    {
        vendor: IETF,
        products: [
            {
                product: IP
                versions: [
                    { version: v4, impact: none }
                    { version: v6, impact: high }
                ]
            },
            {
                product: DHCP
                impact: none
                versions: [
                    { version: v4, impact: none }
                    { version: v6, impact: none }
                ]
            }
        ]
    }
]

```

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
