### ISSUE TITLE
Discussion for changelog container

### ISSUE THREAD

**Issue by kurtseifried** [CVEProject/automation-working-group#33]
It has been suggested we have a changelog in the CVE format, I would suggest we make it a container so it can be part of the root (e.g. global) or a specific section (e.g. Affected-Red Hat-RHEL). It would need some things like a timestamp, changelog content, importance metric maybe? type of changelog? (informational, correction, etc.). Please discuss in this issue.

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
