### ISSUE TITLE
Schema Updates to Support Values of STATE Other than PUBLIC

### ISSUE THREAD

**Issue by theall38103** [CVEProject/automation-working-group#36]
Currently, the schema requires that an entry has information about the affected vendor / product / version, the problem type, and at least one reference. That information isn't available for all CVE ids. For example, when a block reservation happens, MITRE creates ids in the RESERVED state with a templated description. These ids do not, though, have references or information about the affected product(s) and problem type and, as a result, JSON files created for them will fail schema validation currently.

**Comment by anthnysingleton** [comment]
This is both true and false. If you use the mitre-cna-assignment-info.js and implement a way to choose a "reserved" state we can then allow the tool to auto populate the remaining fields with a string such as "not yet available" or "[CNA] has reserved this ID and will provide information at a later time".

So the output file would look like:

```
{
	"data_type": "CVE",
	"data_format": "MITRE",
	"data_version": "4.0",
	"CVE_data_meta": {
		"ID": "CVE-YYYY-NNNNNN"
		"ASSIGNER": "[CNA] address"
	},
	"affects": {
		"vendor": {
			"vendor_data": [
				{
					"vendor_name": "[CNA]",
					"product": {
						"product_data": [
							{
								"product_name": "Not Available",
								"version": {
									"version_data": [
										{
											"version_value": "Not Available"
										}
									]
								}
							}
						]
					}
				}
			]
		}
	},
	"problemtype":{
		"problemtype_data":[
			{
				"description":[
					{
						"lang": "eng",
						"value":"This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided."
					}
				]
			}
		]
	},
	"references":{
		"reference_data":[
			{
				"url":"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-YYYY-XXXX"
			}
		]
	},
	"description":{
		"description_data":[
			{
				"lang": "eng",
				"value":"This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided."
			}
		]
	}
}
```

This way the Reserved CVE JSON file will pass the current validation check against the Schema.

**Comment by kurtseifried** [comment]
We need the following states:

1) PUBLIC
2) RESERVED
3) REJECT

The board had also discussed more states as RESERVED is overloaded. Example include:

REJECT for [specific reason, e.g. WRONG/SPLIT/MERGE/DUPLICATE OF/etc]
RESERVED for [specific reason, e.g. CNA block, not actually used yet]

thoughts and comments?

**Comment by zmanion** [comment]
DEFAULT (ID exists in infinite possibility, possibly master CNA is by default responsible)
RESERVED (Specific CNA is responsible for the ID, ID reserved for use by a CNA by their parent CNA)
ASSIGNED (ID assigned by CNA to a vulnerability. Do CNAs want/need this?)
PUBLIC (entry populated, published)
DISPUTED (
REJECTED (SPLIT_FROM, MERGE_TO, DUPLICATE_OF, WRONG?)

But... this is the bigger state discussion. To fill out JSON, I think the schema only needs to support STATE=PUBLIC? There might be a STATE issue.

1. Create new validation code/option for RESERVED IDs with missing fields.
2. Keep existing validation and fill out placeholder data for required fields, per @anthnysingleton above.

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
