### ISSUE TITLE
Make statement of change control/versioning

### ISSUE THREAD

**Issue by kurtseifried** [CVEProject/automation-working-group#4]
We should post an official statement about versioning, e.g. that within a major version (3.x) we will maintain compatibility (e.g. only adding fields), but if we modify fields or drop them we'll need to bump the revision. Essentially if the JSON schema needs a change then we should increment the major version number (e.g. 3 to 4).

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
