### ISSUE TITLE
CVE - automation

### ISSUE THREAD

**Issue by TigerClaw33** [CVEProject/automation-working-group#46]
Hello,
I am trying to get and filter data from CVE (http://cve.mitre.org/data/downloads/index.html). But I have no experience in this topic. 

I have to possibilities. On way is to write a makro for a google-doc-spreadsheet (is there any example) and the other way seems to be to get the data and convert it from json to cvs. How can I do this with python?

**Comment by kernelsmith** [comment]
google should be able to help you here.  I found many solutions including https://github.com/vinay20045/json-to-csv

@kurtseifried recommend closing this issue
