### ISSUE TITLE
Error validating 'nvdcve-1.0-recent.json' using CVE_JSON_4.0_min.schema  (Python + jsonschema)

### ISSUE THREAD

**Issue by kauedg** [CVEProject/automation-working-group#47]
The validation of 'https://static.nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.json' is failing when using the 'CVE_JSON_4.0_min.schema' schema, in python 3.5 with jsonschema lib.

Code snippet:

```
import json
import jsonschema

feed_file = open("nvdcve-1.0-recent.json").read()
schema_file = open("CVE_JSON_4.0_min.schema").read()

schema = json.loads(schema_file)
feed = json.loads(feed_file)

try:
	jsonschema.validate(feed, schema)
except Exception as ex:
	print(ex)

```

Thrown exception:
```
'data_type' is a required property

Failed validating 'required' in schema:
[schema file content]
[feed file content]

```

**Comment by theall38103** [comment]
According to https://nvd.nist.gov/vuln/Data-Feeds/JSON-feed-changelog, the NVD's JSON data feed uses a schema that extends CVE_JSON_4.0_min.schema. You should instead validate the NVD feed using  nvd_cve_feed_json_0.1_beta.schema, which is referenced in that changelog.
