### ISSUE TITLE
Add data_type field to data

### ISSUE THREAD

**Issue by kurtseifried** [CVEProject/automation-working-group#6]
Currently we only have CVE JSON blobs in here, and that is likely a safe assumption but @DWF we're using JSON for a number of other things (CNAs, CVE Mentors, etc.). Having a data_type field would be handy to declare what this JSON blob is:

  "data_type": "CVE"
  "data_type": "CNA"
  "data_type": "CVE_MENTOR"

and so on, it would make detection of what the JSON is a lot easier.

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
