### ISSUE TITLE
Nested structure versus flat structure

### ISSUE THREAD

**Issue by adulau** [CVEProject/automation-working-group#61]
Interesting work.

Looking at the DRAFT document, I was wondering why there is such a nesting in the JSON format. It's usually cleaner and better to have a non-nested document and make references if needed among the objects. Is there a specific advantages for such nested structure?

**Comment by chandanbn** [comment]
Alexandre, this is a good point. There is some nesting that serves no purpose and complicates both generation and processing of JSON. See #31 

We also want to be flexible in allowing different values for the same field under different contexts. Take CVSS as an example: Different different products or versions may have different CVSS scores for the same vulnerability. Allowing a CVSS score field to be nested inside a particular product or version item allows this. You can also have a top level CVSS score that looks at the problem from an industry wide perspective.

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
