### ISSUE TITLE
Consider adding an references or similar optional field under problemtype_data to allow for including url references about an issue.

### ISSUE THREAD

**Issue by dbaxa** [CVEProject/automation-working-group#63]
Consider adding a references or similar **optional** field under `problemtype_data` to allow for including url references about a problem type. This can be used to link to CWE definition urls.

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
