### ISSUE TITLE
SAWG Charter: Clarify open source, standards

### ISSUE THREAD

**Issue by chandanbn** [CVEProject/automation-working-group#64]
Re: 
> Use open source solutions where possible
> Promote standards and best practices for automated information exchange

Open source does not necessarily mean 'free'. Open source solutions may have restrictions on use, and may prevent some or all of the CVE participants from using them.

Similarly not all standards are free and fair.
Standards may require fees to access them, such as those from ISO.
Some standards may require fees for creation and use, such as SWID tags.

Use of encumbered solutions or standards would be detrimental to other stated charter goals.

Suggestion:

----

Use **free and** open source solutions where possible. **Avoid solutions that require propriety, closed systems, or not compatible with CVE terms of use**.

Promote **free and open** standards and best practices for automated information exchange. **Avoid standards that are not free and not open.**

----

We should design solutions keeping in mind that github.com and git itself may go away at some point in the future. We should plan ahead and be ready to migrate the CVE corpus and automation infrastructure to somewhere else.

**Comment by kentlandfield** [comment]
I agree with the two suggestions.

**Comment by chandanbn** [comment]
Closing this issue as charter now addresses this concern.
