### ISSUE TITLE
Clarify how non-ASCII email addresses should be handled

### ISSUE THREAD

**Issue by theall38103** [CVEProject/automation-working-group#67]
The three state-specific schemas currently test that email addresses match the pattern "^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$".  This won't work for IDNs (Internationalized Domain Names) or Emoji domains. Should the draft spec be updated to require addresses be transcoded to ASCII using Punycode, say?

**Comment by mprpic** [comment]
CVE v5 JSON schema does not include this pattern so I'm assuming this is obsolete. Closing!
