### ISSUE TITLE
Restricting email address TLDs

### ISSUE THREAD

**Issue by theall38103** [CVEProject/automation-working-group#68]
The three state-specific schemas currently test that email addresses match the pattern "^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$".   That will present problems for addresses with some of the newer top-level domains (eg, https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#ICANN-era_generic_top-level_domains). What, if anything, should we use as an upper-bound on the length of the TLD?

**Comment by mprpic** [comment]
CVE v5 JSON schema does not include this pattern so I'm assuming this is obsolete. Closing!
