### ISSUE TITLE
figure out how to list fixed versions/commits/etc

### ISSUE THREAD

**Issue by kurtseifried** [CVEProject/automation-working-group#7]
figure out how to list fixed versions/commits/etc - add to affects? have a "fixed" section? Bring up on board meeting probably.

**Comment by theall38103** [comment]
We should also figure how how to handle multiple release branches for a given product. For affected and fixed versioning.

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
