### ISSUE TITLE
Document How to Join AWG

### ISSUE THREAD

**Issue by theall38103** [CVEProject/automation-working-group#70]
Currently there is no documentation to tell CNAs -- or other interested parties -- how to join the CVE Automation Working Group. There should be.

**Comment by mprpic** [comment]
This is sort of mentioned in https://www.cve.org/ProgramOrganization/WorkingGroups#AutomationWorkingGroupAWG but should probably be replicated in this repo as well. PR for text suggestions welcome!

**Comment by rbrittonMitre** [comment]
The [README.md](https://github.com/CVEProject/automation-working-group/blob/master/README.md) file has been updated to have a section specifically about joining the AWG.  It provides two method to submit a request: (a) send email the AWG list or (b) fill out the web form on the cve.org web site.
