### ISSUE TITLE
unicode is not an encoding - specify utf-8?

### ISSUE THREAD

**Issue by d-hat** [CVEProject/automation-working-group#9]
CVE JSON files are unicode, encoded as UTF-8.  At least the following fields may be unicode:  titles, descriptions, researcher names, version numbers (people use alphabetical versioning, so we should expect this but in other character sets/languages). Data should no longer be assumed to be simple ascii all the time.

**Comment by mprpic** [comment]
This issue is being closed as obsolete. If you feel it is still relevant to any currently running AWG initiatives, feel free to re-open it or open a new issue. Thank you!
